name: 'merck_dv'
version: '1.0.0'
config-version: 2
profile: 'merck_dv'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# =================================================================
# END-OF-RUN HOOK FOR ROW COUNT SUMMARY
# This hook runs AFTER all models have been built, collecting and
# logging the row count for every successfully materialized model.
# =================================================================
on-run-end:
  - "{{ log_all_materialized_row_counts() }}"

# =================================================================
# GLOBAL VARIABLE OVERRIDE FOR DATAVAULT4DBT
# =================================================================
vars:
  datavault4dbt:
    dv_technical_column_names:
      load_timestamp_name: 'load_ts'
      source_column_name: 'rsrc'

# Configuring models (Nested under project name 'merck_dv')
models:
  merck_dv:
    +schema: DBT_DEFAULT 

    # ----------------------------------------------------------------------------------
    # STAGING LAYER (Views)
    # ----------------------------------------------------------------------------------
    stg:
      +schema: DBT_STG
      +materialized: view

    # ----------------------------------------------------------------------------------
    # RAW DATA VAULT (Incremental Models)
    # NOTE: The post-hook for row count is removed and moved to the 'on-run-end' hook above.
    # ----------------------------------------------------------------------------------
    rdv:
      +schema: DBT_RDV
      +materialized: incremental

    # ----------------------------------------------------------------------------------
    # BUSINESS DATA VAULT (Views)
    # ----------------------------------------------------------------------------------
    bdv:
      +schema: DBT_BDV
      +materialized: view

    # ----------------------------------------------------------------------------------
    # CONSUMPTION LAYER (Table Models)
    # NOTE: The post-hook for row count is removed and moved to the 'on-run-end' hook above.
    # ----------------------------------------------------------------------------------
    con:
      +schema: DBT_CON
      +materialized: table